# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

excluded_modules = [
    'tkinter', 'pytest', 'numpy', 'pandas', 'matplotlib',
    'scipy', 'notebook', 'babel', 'docutils', 'sphinx',
    'jupyter', 'IPython'
]

a = Analysis(
    ['app_launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('foodproject', 'foodproject'),
        ('logs', 'logs'),
    ],
    hiddenimports=[
        'django',
        'django.middleware',
        'django.template.defaulttags',
        'django.template.loader_tags',
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.auth.backends',
        'django.contrib.auth.hashers',
        'django.contrib.auth.middleware',
        'django.contrib.contenttypes',
        'django.contrib.contenttypes.models',
        'django.contrib.sessions',
        'django.contrib.sessions.middleware',
        'django.contrib.messages',
        'django.contrib.messages.middleware',
        'django.contrib.staticfiles',
        'django.contrib.staticfiles.finders',
        'django.template.loader',
        'django.db.models.query',
        'django.db.models.fields',
        'django.urls.resolvers',
        'django.views.generic',
        'django.forms',
        'foodproject',
        'foodproject.foodapp',
        'foodproject.foodapp.models',
        'foodproject.foodapp.views',
        'foodproject.foodapp.urls',
        'crispy_forms',
        'webview',
        'webview.platforms.win32',
        'socket',
        'threading',
        'time',
        'subprocess',
        'requests',
        'urllib',
        'urllib.parse',
        'logging',
        'datetime',
        'signal',
        'json',
    ],
    excludes=excluded_modules,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='FoodFlex',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='foodproject/static/foodapp/img/favicon.ico',
    version='file_version_info.txt',
)
