# Generated by Django 5.2 on 2025-04-27 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cities/')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('sweet', 'Sweet'), ('salty', 'Salty'), ('drink', 'Drink')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/')),
                ('bad_for_cholesterol', models.BooleanField(default=False)),
                ('bad_for_sugar', models.BooleanField(default=False)),
                ('bad_for_lactose', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='foodapp.city')),
            ],
        ),
    ]
