# Generated by Django 5.2 on 2025-04-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.CharField(default='hello', max_length=500),
            preserve_default=False,
        ),
    ]
