# Generated by Django 5.2 on 2025-04-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_city_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='price_range',
            field=models.CharField(choices=[('low', '$'), ('medium', '$$'), ('high', '$$$')], default='medium', max_length=10),
        ),
    ]
