# Generated by Django 5.2 on 2025-04-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_dish_is_vegan_dish_is_vegetarian_dish_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='preparation_steps',
            field=models.TextField(blank=True),
        ),
    ]
