# Generated by Django 5.2 on 2025-05-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cultural_notes',
            field=models.TextField(blank=True, help_text='Informations culturelles sur ce plat pour les touristes'),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_tourist_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='origin',
            field=models.CharField(choices=[('moroccan', 'Cuisine Marocaine'), ('italian', 'Cuisine Italienne'), ('french', 'Cuisine Française'), ('japanese', 'Cuisine Japonaise'), ('mexican', 'Cuisine Mexicaine'), ('chinese', 'Cuisine Chinoise'), ('indian', 'Cuisine Indienne'), ('other', 'Autre Cuisine')], default='other', max_length=20),
        ),
    ]
