# Generated by Django 5.2 on 2025-05-20 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.RemoveField(
            model_name='dish',
            name='bad_for_cholesterol',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='bad_for_lactose',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='bad_for_sugar',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='cultural_notes',
        ),
        migrations.RemoveField(
            model_name='restaurantaccount',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='restaurantaccount',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='restaurantaccount',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='capacity',
            field=models.PositiveIntegerField(default=50, help_text='Capacité maximale du restaurant'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='foodapp.city'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='origin',
            field=models.CharField(choices=[('moroccan', 'Marocain'), ('international', 'International'), ('fusion', 'Fusion')], default='moroccan', max_length=20),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price_range',
            field=models.CharField(choices=[('L', 'Abordable'), ('M', 'Modéré'), ('H', 'Premium')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.CharField(choices=[('sweet', 'Sucré'), ('salty', 'Salé'), ('drink', 'Boisson')], default='salty', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guests',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='RestaurantEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('tasting', 'Dégustation'), ('cooking_class', 'Cours de cuisine'), ('special_menu', 'Menu spécial'), ('cultural', 'Événement culturel'), ('other', 'Autre')], max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_participants', models.PositiveIntegerField(default=20)),
                ('registration_required', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='foodapp.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('guests', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attended', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='foodapp.restaurantevent')),
            ],
            options={
                'unique_together': {('event', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='foodapp.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
