# Generated by Django 5.2 on 2025-05-21 16:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0010_alter_city_options_remove_dish_bad_for_cholesterol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantevent',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='dish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='cultural_notes',
            field=models.TextField(blank=True, help_text='Notes culturelles sur ce plat pour les touristes', null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_dishes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dish',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='foodapp.city'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_tourist_recommended',
            field=models.BooleanField(default=False, help_text='Cochez cette case si ce plat est particulièrement recommandé aux touristes'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='origin',
            field=models.CharField(choices=[('moroccan', 'Marocaine'), ('international', 'Internationale'), ('fusion', 'Fusion')], default='moroccan', max_length=20),
        ),
        migrations.AlterField(
            model_name='dish',
            name='preparation_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price_range',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.CharField(choices=[('sweet', 'Sucré'), ('salty', 'Salé'), ('drink', 'Boisson')], max_length=20),
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
        migrations.DeleteModel(
            name='RestaurantEvent',
        ),
    ]
