# Generated by Django 5.2 on 2025-05-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0011_auto_20250521_1719'),
        ('foodapp', '0011_remove_restaurantevent_restaurant_dish_created_at_and_more'),
    ]

    operations = [
    ]
