# Generated by Django 5.2 on 2025-05-21 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0013_forumtopic_forummessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantaccount',
            name='account_type',
            field=models.CharField(choices=[('basic', 'Basique'), ('premium', 'Premium'), ('gold', 'Gold')], default='basic', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurantaccount',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantaccount',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantaccount',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='restaurantaccount',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='restaurantaccount',
            name='theme_preference',
            field=models.CharField(default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantaccount',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RestaurantDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_to_account', models.BooleanField(default=False)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_drafts', to='foodapp.city')),
            ],
        ),
    ]
