# Generated by Django 5.2 on 2025-05-21 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0014_restaurantaccount_account_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('user', 'Utilisateur')], max_length=20)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.JSONField(default=dict)),
                ('is_featured', models.BooleanField(default=False)),
                ('max_listings', models.IntegerField(default=1)),
                ('badge_text', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_percent', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('preparing', 'En préparation'), ('ready', 'Prête'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('paid', 'Payée')], default='new', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('online', 'Paiement en ligne')], default='cash', max_length=20)),
                ('is_takeaway', models.BooleanField(default=False)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('order_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodapp.reservation')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodapp.restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='foodapp.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Actif'), ('canceled', 'Annulé'), ('expired', 'Expiré'), ('trial', 'Essai')], default='active', max_length=20)),
                ('is_auto_renew', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('restaurant_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='foodapp.restaurantaccount')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foodapp.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Actif'), ('canceled', 'Annulé'), ('expired', 'Expiré'), ('trial', 'Essai')], default='active', max_length=20)),
                ('is_auto_renew', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foodapp.subscriptionplan')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='foodapp.userprofile')),
            ],
        ),
    ]
