# Generated by Django 5.2.1 on 2025-05-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0015_subscriptionplan_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_admin_created',
            field=models.BooleanField(default=True, help_text="Indique si le plat a été créé via le panneau d'administration Django"),
        ),
    ]
