# Generated by Django 5.2.1 on 2025-05-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0016_dish_is_admin_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de calories par portion', null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='has_cholesterol',
            field=models.BooleanField(default=False, help_text='Contient du cholestérol élevé'),
        ),
        migrations.AddField(
            model_name='dish',
            name='has_gluten',
            field=models.BooleanField(default=False, help_text='Contient du gluten'),
        ),
        migrations.AddField(
            model_name='dish',
            name='has_lactose',
            field=models.BooleanField(default=False, help_text='Contient du lactose'),
        ),
        migrations.AddField(
            model_name='dish',
            name='has_nuts',
            field=models.BooleanField(default=False, help_text='Contient des noix/arachides'),
        ),
        migrations.AddField(
            model_name='dish',
            name='has_sugar',
            field=models.BooleanField(default=False, help_text='Contient du sucre'),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_diabetic_friendly',
            field=models.BooleanField(default=False, help_text='Adapté aux diabétiques'),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_low_calorie',
            field=models.BooleanField(default=False, help_text='Faible en calories'),
        ),
    ]
