# Generated by Django 5.2.1 on 2025-06-01 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0017_dish_calories_dish_has_cholesterol_dish_has_gluten_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantdraft',
            options={'verbose_name': 'Restaurant en attente', 'verbose_name_plural': 'Restaurants en attente'},
        ),
        migrations.RemoveField(
            model_name='restaurantdraft',
            name='converted_to_account',
        ),
        migrations.RemoveField(
            model_name='restaurantdraft',
            name='features',
        ),
        migrations.AddField(
            model_name='restaurantaccount',
            name='pending_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantdraft',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurantdraft',
            name='business_registration',
            field=models.FileField(blank=True, null=True, upload_to='restaurant_docs/registration/'),
        ),
        migrations.AddField(
            model_name='restaurantdraft',
            name='capacity',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='restaurantdraft',
            name='food_safety_certificate',
            field=models.FileField(blank=True, null=True, upload_to='restaurant_docs/certificates/'),
        ),
        migrations.AddField(
            model_name='restaurantdraft',
            name='interior_image1',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_drafts/interior/'),
        ),
        migrations.AddField(
            model_name='restaurantdraft',
            name='interior_image2',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_drafts/interior/'),
        ),
        migrations.AddField(
            model_name='restaurantdraft',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_drafts/main/'),
        ),
        migrations.AddField(
            model_name='restaurantdraft',
            name='menu_sample',
            field=models.FileField(blank=True, null=True, upload_to='restaurant_drafts/menus/'),
        ),
        migrations.AddField(
            model_name='restaurantdraft',
            name='owner_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='restaurantdraft',
            name='owner_first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurantdraft',
            name='owner_id_card',
            field=models.FileField(blank=True, null=True, upload_to='restaurant_docs/id_cards/'),
        ),
        migrations.AddField(
            model_name='restaurantdraft',
            name='owner_last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurantdraft',
            name='owner_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantdraft',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantdraft',
            name='tax_document',
            field=models.FileField(blank=True, null=True, upload_to='restaurant_docs/tax/'),
        ),
        migrations.AddField(
            model_name='restaurantdraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurantdraft',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurantaccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurantdraft',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurantdraft',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodapp.city'),
        ),
        migrations.AlterField(
            model_name='restaurantdraft',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='restaurantdraft',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='restaurantdraft',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantdraft',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
