# Generated by Django 5.2.1 on 2025-07-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0019_dish_restaurant_restaurantaccount_ban_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil utilisateur', 'verbose_name_plural': 'Profils utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_cuisine',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferences',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.JSONField(blank=True, default=list, help_text="Liste des allergies de l'utilisateur", verbose_name='Allergies alimentaires'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dietary_preference',
            field=models.CharField(blank=True, choices=[('none', 'Aucun régime spécifique'), ('vegetarian', 'Végétarien'), ('vegan', 'Végétalien/Végan'), ('pescatarian', 'Pescétarien'), ('gluten_free', 'Sans gluten'), ('lactose_free', 'Sans lactose'), ('keto', 'Cétogène (Keto)'), ('paleo', 'Paléo'), ('mediterranean', 'Méditerranéen'), ('other', 'Autre')], default='none', max_length=20, verbose_name='Régime alimentaire'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_diabetes',
            field=models.BooleanField(default=False, verbose_name='Diabète'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_high_blood_pressure',
            field=models.BooleanField(default=False, verbose_name='Hypertension artérielle'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_high_cholesterol',
            field=models.BooleanField(default=False, verbose_name='Cholestérol élevé'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_goals',
            field=models.JSONField(blank=True, default=list, help_text="Objectifs de santé de l'utilisateur", verbose_name='Objectifs de santé'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='À propos de moi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_vegan',
            field=models.BooleanField(default=False, verbose_name='Végan'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_vegetarian',
            field=models.BooleanField(default=False, verbose_name='Végétarien'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
    ]
