# Generated by Django 5.2.1 on 2025-07-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0020_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sédentaire'), ('light', 'Légèrement actif'), ('moderate', 'Modérément actif'), ('active', 'Très actif'), ('extreme', 'Extrêmement actif')], default='moderate', max_length=20, verbose_name="Niveau d'activité physique"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='additional_allergies',
            field=models.TextField(blank=True, help_text='Décrivez toute autre allergie ou intolérance non listée ci-dessus', verbose_name='Allergies supplémentaires'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='additional_preferences',
            field=models.TextField(blank=True, help_text="Avez-vous d'autres préférences ou restrictions alimentaires ?", verbose_name='Préférences supplémentaires'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avoids_gmo',
            field=models.BooleanField(default=False, verbose_name='Évite les OGM'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_celiac_disease',
            field=models.BooleanField(default=False, verbose_name='Maladie cœliaque'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_lactose_intolerance',
            field=models.BooleanField(default=False, verbose_name='Intolérance au lactose'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefers_halal',
            field=models.BooleanField(default=False, verbose_name='Préfère la nourriture halal'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefers_kosher',
            field=models.BooleanField(default=False, verbose_name='Préfère la nourriture casher'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefers_organic',
            field=models.BooleanField(default=False, verbose_name='Préfère les produits bio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_goal',
            field=models.CharField(blank=True, choices=[('lose', 'Perdre du poids'), ('maintain', 'Maintenir mon poids'), ('gain', 'Prendre du poids')], default='maintain', max_length=20, verbose_name='Objectif de poids'),
        ),
    ]
