# Generated by Django 5.2.1 on 2025-07-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0021_userprofile_activity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', help_text='Sélectionnez votre langue préférée', max_length=10, verbose_name='Langue préférée'),
        ),
    ]
