# Generated by Django 5.2.1 on 2025-07-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0022_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Préférences utilisateur (thème, notifications, etc.)', verbose_name='Préférences'),
        ),
    ]
