# Generated by Django 5.2.1 on 2025-07-24 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0023_userprofile_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'En attente'), ('preparing', 'En préparation'), ('ready', 'Prêt à servir'), ('served', 'Servi')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_prep_time', models.PositiveIntegerField(blank=True, help_text='Temps estimé de préparation en minutes', null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_status', to='foodapp.order')),
            ],
            options={
                'verbose_name': 'Statut cuisine',
                'verbose_name_plural': 'Statuts cuisine',
                'ordering': ['-updated_at'],
            },
        ),
    ]
